### ISSUE TITLE
Cannot pass options.attributes to textToSVG.getSVG

### ISSUE THREAD

**Issue by maxmagu** [shrhdk/text-to-svg#10]
Running the first example from the readme fails

```javascript
const TextToSVG = require('text-to-svg');
const textToSVG = TextToSVG.loadSync();

const attributes = {fill: 'red', stroke: 'black'};
const options = {x: 0, y: 0, fontSize: 72, anchor: 'top', attributes: attributes};

const svg = textToSVG.getSVG('hello', options);

console.log(svg);
```

with the following error

```
/test/node_modules/text-to-svg/build/src/index.js:146
        return key + '="' + attributes[key] + '"';

TypeError: Cannot read property 'fill' of undefined
```

I think there is a bug in this line: https://github.com/shrhdk/text-to-svg/blob/master/src/index.js#L134

You probably want to read from `options.attributes` instead of `attributes` there.

Great Project, keep it up!

**Comment by shrhdk** [comment]
Oh, man! Thank you very much for detailed report.
I will fix this problem as soon as possible.
