### ISSUE TITLE
Run in the browser?

### ISSUE THREAD

**Issue by villanus** [shrhdk/text-to-svg#11]
I am trying to do something similar with OpenType alone and have had Zero luck. 
We are on a windows IIS setup, without node. 

Can this work int he browser alone?
Will it weld overlapping paths?

**Comment by shrhdk** [comment]
> Can this work in the browser alone?

Yes, I tried text-to-svg on web browsers and it works well.
You have to build this library by [Browserify](http://browserify.org/).

Build script is in [gulpfile.babel.js#L51](https://github.com/shrhdk/text-to-svg/blob/3.0.1/gulpfile.babel.js#L51)

You can build sample script I tried for web browsers by `npm test` command.
After that, you can open `test/browser.html` to try sample script.

> Will it weld overlapping paths?

text-to-svg always outputs one path.

**Comment by shrhdk** [comment]
opentype.js, the base library of text-to-svg provides the distribution for web browsers.

https://github.com/nodebox/opentype.js/tree/0.6.2/dist

#3 is related issue.

**Comment by villanus** [comment]
Thanks.
I will look into the browserify thing.   =)

**Comment by shrhdk** [comment]
Please reopen if you have more questions.
