### ISSUE TITLE
How to write pronunciation along words? 

### ISSUE THREAD

**Issue by edouard-lopez** [shrhdk/text-to-svg#12]
Hi, 
I'm looking into your project to [generate chinese font with pronunciation](https://github.com/edouard-lopez/Hanzi-Pinyin-Font). One of my goal is to write [ruby text](https://www.wikiwand.com/en/Ruby_character), _i.e._ a character and next to it its pronuncuation (as show below):

![furigana example](http://www.learn-japanese-adventure.com/image-files/t3-furigana-rubi.png)

As you can see text can be either vertical or horizontal. 

How can I append text to achieve this using `text-to-svg`?

**Comment by shrhdk** [comment]
`getMetrics` method and `getPath` method allow you to write ruby text.

Sample code is here.

```js
const TextToSVG = require('text-to-svg');
const textToSVG = TextToSVG.loadSync();

const RUBY_HEIGHT = 6;
const CHAR_HEIGHT = 18;

// get path of 日 (に)

const met1 = textToSVG.getMetrics('日', {fontSize: CHAR_HEIGHT});

const ruby1 = textToSVG.getPath('に', {
	fontSize: RUBY_HEIGHT,
	anchor: 'top center',
	x: met1.width / 2,
	y: 0
});

const char1 = textToSVG.getPath('日', {
	fontSize: CHAR_HEIGHT,
	anchor: 'top left',
	x: 0,
	y: RUBY_HEIGHT
});

// get path of 本 (ほん)

const met2 = textToSVG.getMetrics('本', {fontSize: CHAR_HEIGHT});

const ruby2 = textToSVG.getPath('ほん', {
	fontSize: RUBY_HEIGHT,
	anchor: 'top center',
	x: met1.width + met2.width / 2,
	y: 0
});

const char2 = textToSVG.getPath('本', {
	fontSize: CHAR_HEIGHT,
	anchor: 'top left',
	x: met1.width,
	y: RUBY_HEIGHT
});

// get SVG

const width = met1.width + met2.width;
const height = RUBY_HEIGHT + CHAR_HEIGHT;

var svg = '<svg ';
svg += 'width="' + width + '" ';
svg += 'height="' + height +'">';
svg += ruby1;
svg += char1;
svg += ruby2;
svg += char2;
svg += '</svg>';

console.log(svg);
```

Result is here.

<img width="363" alt="nihon" src="https://cloud.githubusercontent.com/assets/1025020/17698867/7b3923ca-63f8-11e6-8ea2-9825fe0f5823.png">
