### ISSUE TITLE
Letter-spacing, word-spacing

### ISSUE THREAD

**Issue by l00mi** [shrhdk/text-to-svg#15]
Is it possible to set the spacing like in this [example](http://vanseodesign.com/web-design/svg-text-spacing-properties/)?

**Comment by shrhdk** [comment]
No, they are not implemented. You can only use kerning option.

**Comment by l00mi** [comment]
Thank you for the fast answer! How difficult do you think it will be to make this possible?

It seems that the letter-spacing [functionality](https://github.com/nodebox/opentype.js/blob/a95e2ecd8901800cd84b60117c73f24b13925ca1/src/font.js#L239) is already in opentype.js can this be used?

**Comment by shrhdk** [comment]
Thank you for the hot information.

It will be easy to support letter-spacing option, by editing below line.

https://github.com/shrhdk/text-to-svg/blob/a5c1b08a3f6b0592ed2f9562e5791e1b2995a727/src/index.js#L127

But currently letter-spacing support has not been released yet in opentype.js.

https://github.com/nodebox/opentype.js/blob/0.6.5/src/font.js#L219

We have to wait for its release.

**Comment by l00mi** [comment]
Oh, this I did not even realise. Fair enough lets wait until there is the [release](https://github.com/nodebox/opentype.js/releases/tag/0.6.6).

**Comment by l00mi** [comment]
The fine folks at https://github.com/nodebox/opentype.js were nice enough to make the new  [release](https://github.com/nodebox/opentype.js/releases/tag/0.6.6). 

Hope I find to make a pull request soon.

**Comment by l00mi** [comment]
Anything blocking to integrate this functionality? I like to keep using your version of text-to-svg in my projects.

**Comment by shrhdk** [comment]
I'm sorry to my late response. Your PR is perfect.

I will make new release soon.

**Comment by l00mi** [comment]
Thank you, perfect timing!
