### ISSUE TITLE
Random Errors when calling .load

### ISSUE THREAD

**Issue by nearAP** [shrhdk/text-to-svg#26]
I have a call
`TextToSVG.load(fontPath, function(err, textToSVG) {}`

The err function is randomly triggered. For example, I use the same font and it could work X times and then trigger the error the X + 1 time and work again if called the X + 2 time.

Any idea what could be wrong? Is there a gotcha somewhere or some specific but minor thing that must be done?

**Comment by shrhdk** [comment]
Hi @nearAP,

`load` method retrieves the font data over the network. Whether it succeed or fail depends on network quality, server settings and any factors. Please try it with small file size font data or using CDN.

**Comment by nearAP** [comment]
Ok. Thanks.
