### ISSUE TITLE
not support Chinese?

### ISSUE THREAD

**Issue by WPDreamMelody** [shrhdk/text-to-svg#28]
## Like this : 
const TextToSVG = require('text-to-svg');
const textToSVG = TextToSVG.loadSync();
 
const attributes = {fill: '#FF6633', stroke: '#FF6633'};
const options = {x: 0, y: 0, fontSize: 44, anchor: 'top', attributes: attributes};
 
const svg = textToSVG.getSVG('产品经理',options);
console.log(svg);

**Comment by WPDreamMelody** [comment]
![image](https://user-images.githubusercontent.com/3898789/35546816-d5c65e92-05b0-11e8-9004-2153ceb248d9.png)

**Comment by shrhdk** [comment]
@WPDreamMelody 

The default font does not support Chinese.
Please specify the chinese font to the constructor.

```js
const TextToSVG = require('text-to-svg');
const textToSVG = TextToSVG.loadSync('chinese-font-file.otf');
```

**Comment by WPDreamMelody** [comment]
thanks! change font can success .
