### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by foria** [shrhdk/text-to-svg#3]
Hello, thanks for your work.
I'm just trying to use it but I don't know how to start :(
Sorry I have not so much experience with require libraries etc. but usually I use Gulp.
I tried to include index.js in a html file and checking to console log I got errors.

Please can you help me?

Thanks

**Comment by shrhdk** [comment]
Sorry, text-to-svg does not support web browsers.

[opentype.js](https://github.com/nodebox/opentype.js), the base library of text-to-svg supports web browsers. And opentype.js supports SVG path by now. Please consider to use opentype.js.

The difference between opentype.js and text-to-svg is anchor option.
