### ISSUE TITLE
转换中文时不对,utf-8?

### ISSUE THREAD

**Issue by hktalent** [shrhdk/text-to-svg#31]
转换中文时不对,utf-8?
svg = textToSVG.getSVG("鸔 鸕 鸖 鸗 鸘 鸙",{
		// x:0,y:0,
		fontSize:72,
		// kerning:true,
		// letterSpacing:0,
		anchor:'center'
	});

**Comment by jeffontheground** [comment]
What is the font file parsed to the textToSVG ? Maybe your font file doesn't contain those uncommon word.
and what is the error? Please describe it more.

BTW, to show respect for others, please remove commented code and **translate your question** even if I could read Simplified Chinese.

**Comment by hktalent** [comment]
@jeffontheground china char fonts
