### ISSUE TITLE
Don't want a double lined path

### ISSUE THREAD

**Issue by shashankkala** [shrhdk/text-to-svg#34]
Hi,
I am looking for the SVG path to be a single lined path like below:

![screenshot from 2018-05-24 18-08-20](https://user-images.githubusercontent.com/36631869/40485932-7ac12c6c-5f7d-11e8-8a67-b309f76b52ee.png)

Currently,
It generates a double lined path like this : 

![screenshot from 2018-05-24 18-09-50](https://user-images.githubusercontent.com/36631869/40486021-ba943fdc-5f7d-11e8-9a20-71d065e120b3.png)

<br><br><br>
Is it possible to generate a single lined path like that in the first image that I have attached ?

**Comment by xseignard** [comment]
Hello @shashankkala did you have any success?
