### ISSUE TITLE
Support fonts from URL

### ISSUE THREAD

**Issue by shrhdk** [shrhdk/text-to-svg#7]

**Comment by thierryskoda** [comment]
Hi @shrhdk, 

I can't find a way to load fonts from URL. Example, if I have a lambda function on AWS and I want to go load a font from another server, how would I do it?

Thank you very much!
Thierry

**Comment by pentacular** [comment]
Node also cannot load fonts by url.

Exposing the underlying parse interface of opentype would allow the caller to solve the problem.
